In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('sleeping-alone-data.txt', encoding='ISO-8859-1')

In [224]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

**Replacing the old column names to new names**

In [177]:
new_col_name = ['StartDate','EndDate','CurrentRelationshipStatus', 'RelationshipLength','Frequency in separate beds',
                'YouSleepAt','OtherPlace','PartnerSleepAt','PartnerOtherPlace','Reason_One of us snores',
                'Reason_One of us makes frequent bathroom trips in the night',
                'Reason_One of us is sick','Reason_We are no longer physically intimate',
                'Reason_We have different temperature preferences for the room',
                'Reason_We have had an argument or fight','Reason_Not enough space',
                'Reason_Do not want to share the covers','Reason_One of us needs to sleep with a child',
                'Reason_Night working/very different sleeping times','Reason_Other',
                'First time in separate beds', 'Sleeping in separate beds helps us to stay together',
                'We sleep better when we sleep in separate beds', 'Our sex life has improved as a result of sleeping in separate beds',
                'Occupation','Other Occupation','Gender','Age','Household income','Education','Location']

old_col_name = data.columns

replace_name = dict(zip(old_col_name, new_col_name))

In [188]:
df = data.copy().rename(columns = replace_name)

In [189]:
df.drop(0, axis=0, inplace=True)

**Replace other occupation to the actual occupation**

In [190]:
for i in range(1,len(df['Occupation'])):
    if df['Occupation'][i] == 'Other (please specify)':
        df['Occupation'][i] = df['Other Occupation'][i]

df.drop('Other Occupation', axis = 1, inplace=True)

**Replace different groups into number**

In [191]:
df['Household income'].value_counts()

df['Household income'] = df['Household income'].fillna('Did not disclose')
df['Household income_code'] = df['Household income'].map({'$0 - $24,999':1, '$25,000 - $49,999':2, '$50,000 - $99,999':3, 
                                                        '$100,000 - $149,999':4, '$150,000+':5, 'Did not disclose':0})

In [192]:
df['Age'].value_counts()

df['Age'] = df['Age'].fillna('Did not disclose')
df['Age_code'] = df['Age'].map({'18-29':1, '30-44':2, '45-60':3, '> 60':4, 'Did not disclose':0})

In [193]:
df['Education'].value_counts()

df['Education'] = df['Education'].fillna('Did not disclose')
df['Education_code'] = df['Education'].map({'Graduate degree':5, 'Bachelor degree':4, 'Some college or Associate degree':3,
                                            'High school degree':2, 'Less than high school degree':1, 'Did not disclose':0})

In [194]:
df['Gender'].value_counts()
# female:1 male:0

df['Gender'] = df['Gender'].fillna('Did not disclose')
df['Gender_code'] = df['Gender'].map({'Male':0, 'Female':1, 'Did not disclose':2})

In [213]:
df['Location'] = df['Location'].fillna('Did not disclose')
df['Occupation'] = df['Occupation'].fillna('Did not disclose')

In [214]:
df

,StartDate,EndDate,CurrentRelationshipStatus,RelationshipLength,Frequency in separate beds,YouSleepAt,OtherPlace,PartnerSleepAt,PartnerOtherPlace,Reason_One of us snores,Reason_One of us makes frequent bathroom trips in the night,Reason_One of us is sick,Reason_We are no longer physically intimate,Reason_We have different temperature preferences for the room,Reason_We have had an argument or fight,Reason_Not enough space,Reason_Do not want to share the covers,Reason_One of us needs to sleep with a child,Reason_Night working/very different sleeping times,Reason_Other,First time in separate beds,Sleeping in separate beds helps us to stay together,We sleep better when we sleep in separate beds,Our sex life has improved as a result of sleeping in separate beds,Occupation,Gender,Age,Household income,Education,Location,Household income_code,Age_code,Education_code,Gender_code
1,7/10/14 18:37,7/10/14 18:39,"Single, but cohabiting with a significant other",1-5 years,Once a year or less,On the couch/chair,NaN,"My partner sleeps in our shared bed, I'm the o...",NaN,NaN,NaN,One of us is sick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify),Within the first 1-5 years of our relationship,Strongly disagree,Somewhat agree,Strongly disagree,Student,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,1,1,3,0
2,7/10/14 15:54,7/10/14 15:56,"Single, but cohabiting with a significant other",1-5 years,A few times per month,"I sleep in our shared bed, my partner is the o...",NaN,Separate bedroom,NaN,One of us snores,One of us makes frequent bathroom trips in the...,One of us is sick,NaN,NaN,We've had an argument or fight,NaN,Do not want to share the covers,NaN,NaN,NaN,Immediately/ We've always slept in separate beds,Somewhat agree,Strongly agree,Strongly disagree,Healthcare Support Occupations,Male,18-29,Did not disclose,Bachelor degree,South Atlantic,0,1,4,0
3,7/10/14 15:44,7/10/14 15:49,Married,1-5 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Legal Occupations,Male,18-29,"$150,000+",Graduate degree,South Atlantic,5,1,5,0
4,7/10/14 13:47,7/10/14 13:47,Married,1-5 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Life, Physical, and Social Science Occupations",Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic,2,1,4,0
5,7/10/14 13:13,7/10/14 13:14,Married,1-5 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,Male,18-29,"$100,000 - $149,999",Graduate degree,South Atlantic,4,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,7/9/14 17:46,7/9/14 17:49,Married,Less than 1 year,Once a year or less,"I sleep in our shared bed, my partner is the o...",NaN,Separate bedroom,NaN,One of us snores,One of us makes frequent bathroom trips in the...,One of us is sick,NaN,We have different temperature preferences for ...,We've had an argument or fight,NaN,NaN,NaN,Night working/very different sleeping times,NaN,Within the first 1-5 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,"Arts, Design, Entertainment, Sports, and Media...",Female,30-44,Did not disclose,Bachelor degree,South Atlantic,0,2,4,1
1090,7/9/14 17:46,7/9/14 17:49,Married,More than 20 years,Every night,On the couch/chair,NaN,"My partner sleeps in our shared bed, I'm the o...",NaN,NaN,NaN,NaN,NaN,We have different temperature preferences for ...,NaN,NaN,NaN,NaN,NaN,NaN,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,retired,Male,> 60,Did not disclose,High school degree,East North Central,0,4,2,0
1091,7/9/14 17:46,7/9/14 17:47,Married,1-5 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Management Occupations,Male,30-44,"$150,000+",Bachelor degree,Middle Atlantic,5,2,4,0
1092,7/9/14 17:45,7/9/14 17:46,Separated,16-20 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Arts, Design, Entertainment, Sports, and Media...",Male,> 60,"$50,000 - $99,999",Some college or Associate degree,New England,3,4,3,0
1093,7/9/14 17:45,7/9/14 17:46,Married,More than 20 years,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Office and Administrative Support Occupations,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,West North Central,4,3,3,1

## Demographic data

In [215]:
demographic = df[['CurrentRelationshipStatus', 'RelationshipLength','Frequency in separate beds','Occupation','Gender',
                    'Age','Household income','Education','Location','Gender_code','Age_code','Household income_code','Education_code']]

In [247]:
demographic.to_csv('Demographic_data.csv')

## Separate the data into two subsets: one is sleeping together, the other is separate.

In [217]:
separate_df = df[df['Frequency in separate beds'] != 'Never']
together_df = df[df['Frequency in separate beds'] == 'Never']

### Cleaning together data

507 sleeping separately

586 sleep together

In [218]:
together_df = together_df[['StartDate','EndDate','CurrentRelationshipStatus', 'RelationshipLength','Frequency in separate beds',
                'Occupation','Gender','Age','Household income','Education','Location','Gender_code','Age_code','Household income_code',
                'Education_code']]

In [219]:
together_df.isna().sum()

StartDate                     0
EndDate                       0
CurrentRelationshipStatus     0
RelationshipLength            0
Frequency in separate beds    0
Occupation                    0
Gender                        0
Age                           0
Household income              0
Education                     0
Location                      0
Gender_code                   0
Age_code                      0
Household income_code         0
Education_code                0
dtype: int64

In [248]:
together_df.to_csv("sleep_together.csv")

### Cleaning separate data

In [225]:
separate_df.isna().sum()

StartDate                                                               0
EndDate                                                                 0
CurrentRelationshipStatus                                               0
RelationshipLength                                                     14
Frequency in separate beds                                             14
YouSleepAt                                                             25
OtherPlace                                                            480
PartnerSleepAt                                                         25
PartnerOtherPlace                                                     486
Reason_One of us snores                                                 0
Reason_One of us makes frequent bathroom trips in the night             0
Reason_One of us is sick                                                0
Reason_We are no longer physically intimate                             0
Reason_We have different temperature preferences for the room           0
Reason_We have had an argument or fight                                 0
Reason_Not enough space                                                 0
Reason_Do not want to share the covers                                  0
Reason_One of us needs to sleep with a child                            0
Reason_Night working/very different sleeping times                      0
Reason_Other                                                            0
First time in separate beds                                            25
Sleeping in separate beds helps us to stay together                    26
We sleep better when we sleep in separate beds                         26
Our sex life has improved as a result of sleeping in separate beds     26
Occupation                                                              0
Gender                                                                  0
Age                                                                     0
Household income                                                        0
Education                                                               0
Location                                                                0
Household income_code                                                   0
Age_code                                                                0
Education_code                                                          0
Gender_code                                                             0
dtype: int64

In [221]:
separate_reasons =['Reason_One of us snores',
                'Reason_One of us makes frequent bathroom trips in the night',
                'Reason_One of us is sick','Reason_We are no longer physically intimate',
                'Reason_We have different temperature preferences for the room',
                'Reason_We have had an argument or fight','Reason_Not enough space',
                'Reason_Do not want to share the covers','Reason_One of us needs to sleep with a child',
                'Reason_Night working/very different sleeping times','Reason_Other']

separate_df[separate_reasons] = separate_df[separate_reasons].fillna(0)

for reason in separate_reasons:
    separate_df[reason][separate_df[reason] != 0] = 1

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/var/folders/ll/8lbgzmss0nv0k1lfwjml2h8m0000gn/T/ipykernel_31383/2551898736.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  separate_df[reason][separate_df[reason] != 0] = 1
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:8870: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [118]:
QA = ['Sleeping in separate beds helps us to stay together','We sleep better when we sleep in separate beds', 
    'Our sex life has improved as a result of sleeping in separate beds']

for question in QA:
    separate_df[question] = separate_df[question].fillna(0)
    separate_df[question] = separate_df[question].map({'Strongly disagree':5, 'Somewhat agree':4,'Neither agree nor disagree':3, 
                                     'Strongly agree':2,'Somewhat disagree':1})
    
separate_df['Sleeping in separate beds helps us to stay together'].fillna(0)

1       5.0
2       4.0
3       0.0
4       0.0
5       0.0
       ...
1089    3.0
1090    3.0
1091    0.0
1092    0.0
1093    0.0
Name: Sleeping in separate beds helps us to stay together, Length: 1093, dtype: float64

In [ ]:
separate_reasons =['Reason_One of us snores',
                'Reason_One of us makes frequent bathroom trips in the night',
                'Reason_One of us is sick','Reason_We are no longer physically intimate',
                'Reason_We have different temperature preferences for the room',
                'Reason_We have had an argument or fight','Reason_Not enough space',
                'Reason_Do not want to share the covers','Reason_One of us needs to sleep with a child',
                'Reason_Night working/very different sleeping times','Reason_Other']

df[separate_reasons] = df[separate_reasons].fillna(0)

for reason in separate_reasons:
    df[reason][df[reason] != 0] = 1

In [234]:
separate_df['Sleeping in separate beds helps us to stay together_code'] = separate_df['Sleeping in separate beds helps us to stay together'].map({
    'Strongly agree':5, 'Somewhat agree':4, 'Neither agree nor disagree':3, 'Somewhat disagree':2, 'Strongly disagree':1
})

/var/folders/ll/8lbgzmss0nv0k1lfwjml2h8m0000gn/T/ipykernel_31383/211437129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  separate_df['Sleeping in separate beds helps us to stay together_code'] = separate_df['Sleeping in separate beds helps us to stay together'].map({

In [236]:
separate_df['We sleep better when we sleep in separate beds_code'] = separate_df['We sleep better when we sleep in separate beds'].map({
    'Strongly agree':5, 'Somewhat agree':4, 'Neither agree nor disagree':3, 'Somewhat disagree':2, 'Strongly disagree':1
})

/var/folders/ll/8lbgzmss0nv0k1lfwjml2h8m0000gn/T/ipykernel_31383/2138757153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  separate_df['We sleep better when we sleep in separate beds_code'] = separate_df['We sleep better when we sleep in separate beds'].map({

In [237]:
separate_df['Our sex life has improved as a result of sleeping in separate beds_code'] = separate_df['Our sex life has improved as a result of sleeping in separate beds'].map({
    'Strongly agree':5, 'Somewhat agree':4, 'Neither agree nor disagree':3, 'Somewhat disagree':2, 'Strongly disagree':1
})

/var/folders/ll/8lbgzmss0nv0k1lfwjml2h8m0000gn/T/ipykernel_31383/396426464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  separate_df['Our sex life has improved as a result of sleeping in separate beds_code'] = separate_df['Our sex life has improved as a result of sleeping in separate beds'].map({

In [240]:
separate_df.drop(['OtherPlace', 'PartnerOtherPlace'], axis=1, inplace=True)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [244]:
separate_df['YouSleepAt'].value_counts()

Separate bedroom                                                              185
On the couch/chair                                                            149
I sleep in our shared bed, my partner is the one who sleeps somewhere else    106
Other (please specify)                                                         27
Shared bedroom, different bed                                                  12
Shared bedroom, but one of us sleeps on the floor                               3
Name: YouSleepAt, dtype: int64

In [256]:
separate_df.dropna(inplace=True)

,StartDate,EndDate,CurrentRelationshipStatus,RelationshipLength,Frequency in separate beds,YouSleepAt,PartnerSleepAt,Reason_One of us snores,Reason_One of us makes frequent bathroom trips in the night,Reason_One of us is sick,Reason_We are no longer physically intimate,Reason_We have different temperature preferences for the room,Reason_We have had an argument or fight,Reason_Not enough space,Reason_Do not want to share the covers,Reason_One of us needs to sleep with a child,Reason_Night working/very different sleeping times,Reason_Other,First time in separate beds,Sleeping in separate beds helps us to stay together,We sleep better when we sleep in separate beds,Our sex life has improved as a result of sleeping in separate beds,Occupation,Gender,Age,Household income,Education,Location,Household income_code,Age_code,Education_code,Gender_code,Sleeping in separate beds helps us to stay together_code,We sleep better when we sleep in separate beds_code,Our sex life has improved as a result of sleeping in separate beds_code
1,7/10/14 18:37,7/10/14 18:39,"Single, but cohabiting with a significant other",1-5 years,Once a year or less,On the couch/chair,"My partner sleeps in our shared bed, I'm the o...",0,0,1,0,0,0,0,0,0,0,1,Within the first 1-5 years of our relationship,Strongly disagree,Somewhat agree,Strongly disagree,Student,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific,1,1,3,0,1.0,4.0,1.0
2,7/10/14 15:54,7/10/14 15:56,"Single, but cohabiting with a significant other",1-5 years,A few times per month,"I sleep in our shared bed, my partner is the o...",Separate bedroom,1,1,1,0,0,1,0,1,0,0,0,Immediately/ We've always slept in separate beds,Somewhat agree,Strongly agree,Strongly disagree,Healthcare Support Occupations,Male,18-29,Did not disclose,Bachelor degree,South Atlantic,0,1,4,0,4.0,5.0,1.0
13,7/9/14 23:42,7/9/14 23:45,Married,6-10 years,Once a month or less,On the couch/chair,Separate bedroom,1,0,0,0,0,0,0,0,0,0,0,Within 6-10 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Somewhat disagree,"Arts, Design, Entertainment, Sports, and Media...",Male,30-44,"$100,000 - $149,999",Bachelor degree,West North Central,4,2,4,0,3.0,3.0,2.0
16,7/9/14 23:38,7/9/14 23:42,Married,16-20 years,A few times per week,Separate bedroom,"My partner sleeps in our shared bed, I'm the o...",0,0,0,0,1,0,0,0,0,0,1,Within 11-15 years of our relationship,Strongly agree,Strongly agree,Somewhat agree,Healthcare Practitioners and Technical Occupat...,Male,30-44,"$50,000 - $99,999",Graduate degree,Mountain,3,2,5,0,5.0,5.0,4.0
17,7/9/14 23:38,7/9/14 23:41,Married,6-10 years,Once a year or less,On the couch/chair,"My partner sleeps in our shared bed, I'm the o...",0,0,1,0,0,0,0,0,1,0,0,Within the first 1-5 years of our relationship,Neither agree nor disagree,Somewhat disagree,Strongly disagree,fire service,Male,30-44,"$50,000 - $99,999",Some college or Associate degree,Mountain,3,2,3,0,3.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,7/9/14 17:48,7/9/14 17:50,Married,More than 20 years,A few times per week,Separate bedroom,Separate bedroom,1,0,0,0,1,0,0,0,0,0,0,After 20 years of our relationship,Neither agree nor disagree,Strongly agree,Somewhat agree,Community and Social Service Occupations,Female,45-60,"$100,000 - $149,999",Graduate degree,East North Central,4,3,5,1,3.0,5.0,4.0
1078,7/9/14 17:48,7/9/14 17:50,Married,More than 20 years,Every night,On the couch/chair,On the couch/chair,0,0,1,0,0,0,0,0,0,0,0,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Healthcare Support Occupations,Female,> 60,"$100,000 - $149,999",Some college or Associate degree,Pacific,4,4,3,1,3.0,3.0,3.0
1087,7/9/14 17:47,7/9/14 17:48,Married,11-15 years,A few times per month,"I sleep in our shared bed, my partner is the o...",On the couch/chair,0,0,1,0,0,1,0,0,0,0,1,Within 6-10 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Office and Administrative Support Occupations,Female,30-44,Did not disclose,Some college or Associate degree,Mountain,0,2,3,1,3.0,3.0,3.0
1089,7/9/14 17:46,7/9/14 17:49,Married,Less than 1 year,Once a year or less,"I sleep in our shared bed, my partner is the o...",Separate bedroom,1,1,1,0,1,1,0,0,0,1,0,Within the first 1-5 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,"Arts, Design, Entertainment, Sports, and Media...",Female,30-44,Did not disclose,Bachelor degree,South Atlantic,0,2,4,1,3.0,3.0,3.0
1090,7/9/14 17:46,7/9/14 17:49,Married,More than 20 years,Every night,On the couch/chair,"My partner sleeps in our shared bed, I'm the o...",0,0,0,0,1,0,0,0,0,0,0,After 20 years of our relationship,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,retired,Male,> 60,Did not disclose,High school degree,East North Central,0,4,2,0,3.0,3.0,3.0

In [257]:
separate_df.to_csv('sleep_separately.csv')